### ISSUE TITLE
Tracker for state of CUDA managed/async memory support

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucx-py#892]
This is a meta issue to track the state of CUDA managed and async memory support.

- [x] Add `cudaMallocAsync` support: done in https://github.com/openucx/ucx/pull/8623, available starting from UCX 1.14+)
- [x] Enable CUDA IPC/IB support via UCX staging buffers (`UCX_RNDV_SCHEME=auto UCX_RNDV_FRAG_MEM_TYPE=cuda`): done in https://github.com/rapidsai/ucx-py/pull/836
- [ ] Enable CUDA IPC support in UCX without requiring staging buffers: will require UCX protov2
- [ ] Enable IB support in UCX without requiring staging buffers: not supportes by CUDA yet
- [ ] Fix crashes with non-IB systems when using `UCX_RNDV_FRAG_MEM_TYPE=cuda`: blocked by https://github.com/openucx/ucx/issues/8639, will land with UCX protov2 (default in UCX 1.16)
- [x] Fix crash with CUDA managed memory (only seems to occur if memory is evicted): blocked by https://github.com/openucx/ucx/issues/8669

**Comment by pentschev** [comment]
Latest UCX versions support CUDA managed and async memory via staging buffers. That is automatically enabled under the right circumstances and can be forced with `UCX_RNDV_FRAG_MEM_TYPES=cuda`, closing.
